#love 
love = []
love1 = input("Что для Вас любовь? ")
love.append(love1)
love2 = input("Что для Вас любовь? ")
love.append(love2)
love3 = input("Что для Вас любовь? ")
love.append(love3)
love4 = input("Что для Вас любовь? ")
love.append(love4)
love5 = input("Что для Вас любовь? ")
love.append(love5)
love6 = input("Что для Вас любовь? ")
love.append(love6)
love7 = input("Что для Вас любовь? ")
love.append(love7)
love8 = input("Что для Вас любовь? ")
love.append(love8)
love9 = input("Что для Вас любовь? ")
love.append(love9)
print(f"Для Вас любовь - {love}")

#religion
religion = []
religion1 = input("Что для Вас религия? ")
religion.append(religion1)
religion2 = input("Что для Вас религия? ")
religion.append(religion2)
religion3 = input("Что для Вас религия? ")
religion.append(religion3)
religion4 = input("Что для Вас религия? ")
religion.append(religion4)
religion5 = input("Что для Вас религия? ")
religion.append(religion5)
religion6 = input("Что для Вас религия? ")
religion.append(religion6)
religion7 = input("Что для Вас религия? ")
religion.append(religion7)
religion8 = input("Что для Вас религия? ")
religion.append(religion8)
religion9 = input("Что для Вас религия? ")
religion.append(religion9)
print(f"Для Вас религия - {religion}")

#cosmos
cosmos = []
cosmos1 = input("Что такое космос? ")
cosmos.append(cosmos1)
cosmos1 = input("Что такое космос? ")
cosmos.append(cosmos1)
cosmos2 = input("Что такое космос? ")
cosmos.append(cosmos2)
cosmos3 = input("Что такое космос? ")
cosmos.append(cosmos3)
cosmos4 = input("Что такое космос? ")
cosmos.append(cosmos4)
cosmos5 = input("Что такое космос? ")
cosmos.append(cosmos5)
cosmos6 = input("Что такое космос? ")
cosmos.append(cosmos6)
cosmos7 = input("Что такое космос? ")
cosmos.append(cosmos7)
cosmos8 = input("Что такое космос? ")
cosmos.append(cosmos8)
cosmos9 = input("Что такое космос? ")
cosmos.append(cosmos9)
print(f"Ваши ответы по космосу: {cosmos}")

#cars
cars = []
lovely_car1 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car1)
lovely_car2 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car2)
lovely_car3 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car3)
lovely_car4 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car4)
lovely_car5 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car5)
lovely_car6 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car6)
lovely_car7 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car7)
lovely_car8 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car8)
lovely_car9 = input("Ваша любимая машина 1-  ")
cars.append(lovely_car9)
print(f"your lovely cars list - {cars}")

#nature
nature = []
nature1 = input("Nature for you is: ")
nature.append(nature1)
nature2 = input("Nature for you is: ")
nature.append(nature2)
nature3 = input("Nature for you is: ")
nature.append(nature3)
nature4 = input("Nature for you is: ")
nature.append(nature4)
nature5 = input("Nature for you is: ")
nature.append(nature5)
nature6 = input("Nature for you is: ")
nature.append(nature6)
nature7 = input("Nature for you is: ")
nature.append(nature7)
nature8 = input("Nature for you is: ")
nature.append(nature8)
nature9 = input("Nature for you is: ")
nature.append(nature9)
print(f"Nature for you is: {nature}")
